services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm ci || npm install && npx ng serve --host 0.0.0.0 --poll=2000"
volumes:
  node_modules:
